### ISSUE TITLE
support templates via text/template

### ISSUE THREAD

**Issue by mvdan** [drone-plugins/drone-slack#70]
I want to use a custom template, but I don't want to learn the raymond templating language that this plugin uses. Most Go developers should already be used to text/template, so it should be available as an option.

I would personally just use text/template directly, but I assume that's not an option, which is why I am suggesting supporting both.

Possibly related to #68 - /cc @mmlb

**Comment by bradrydzewski** [comment]
> but I don't want to learn the raymond templating language. 

Raymond is the name of the package. The name of the template language is Mustache / Handlebars. It was chosen because it is language agnostic and more well known than the Go template language among the broader development community.

[1] http://mustache.github.io/

> I don't want to learn the raymond templating language that this plugin uses.

I do not think this is a good enough reason to change the template language. If we use a Go-specific template language we will isolate non-Go developers. The non-Go developers will complain they have to learn the Go template language.

I am open to discussions about a change to the template language, but that discussion would need to focus on technical merit and it would need to demonstrate that it is better for the community as a whole, and not just Go developers.

> I would personally just use text/template directly, but I assume that's not an option, which is why I am suggesting supporting both.

I prefer to standardize and use a single template language across the official plugins.

**Comment by mvdan** [comment]
If you would prefer to use a single template language, then there is no discussion to be had - surely it's not possible to break everyone's setup by changing the template language.

I understand that Go users aren't the only target for Drone, but it's fair to assume that a good portion of them are. For example, one of the reasons I picked Drone is its language - I know it's likely going to be light, easy to deploy, and easy to hack.

Is there a reason not to support the two templating languages, besides consistency/simplicity? I imagine it would be fairly trivial since it's part of the standard library.

**Comment by gtaylor** [comment]
> Is there a reason not to support the two templating languages, besides consistency/simplicity?

Complexity on the code side. Having to support (the users) of multiple templating languages. Having to provide examples of both. Confusing some users as to which to use.

Mustache/Handlebars are everywhere, and it only takes a few minutes to learn how to use them.

And really: Go is an implementation detail. Drone happens to be written in Go, but it's not a Go-specific CI product (we run tons of Python/JS/Java builds/tests through it with good results). Go should not leak its Go internals out to the users unless there are compelling reasons.

**Comment by mvdan** [comment]
Thank you both for the replies - there doesn't seem to be anything to do here, then.

I wish that more things were configurable globally, such as what template library to use. But it's not the end of the world if this is hard-coded to one template library.

**Comment by tboerger** [comment]
> I wish that more things were configurable globally, such as what template library to use. But it's not the end of the world if this is hard-coded to one template library.

But Drone welcomes forks of the plugins to integrate custom features. So feel free to fork the plugin and change the templating, you got the freedom ;)
